ARG BASE_VERSION="41"

FROM ghcr.io/gbraad-devenv/fedora-golang/base:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/fedora"

USER gbraad

ENTRYPOINT [ "/bin/zsh" ]