ARG BASE_IMAGE="ghcr.io/gbraad-devenv/fedora-golang/base"
ARG BASE_VERSION="41"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/fedora"

USER gbraad

ENTRYPOINT [ "/bin/zsh" ]