ARG BASE_IMAGE="ghcr.io/gbraad-devenv/fedora/dotfiles"
ARG BASE_VERSION="41"

FROM ${BASE_IMAGE}:${BASE_VERSION}

USER root

RUN dnf install -y --setopt=tsflags=nodocs \
        delve \
        golang \
        golang-bin \
    && dnf clean all \
    && rm -rf /var/cache/yum

USER root

RUN systemctl enable tailscaled

ENTRYPOINT ["/sbin/init"]
#CMD ["/sbin/init"]