name: build process
run-name: Build process

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:
  build-and-push-base:
    name: Build and push - Fedora Golang container
    uses: ./.github/workflows/reusable-build-and-push-container.yml
    with:
      container_name: "base"
    secrets: inherit

  build-diskimage-fedora-machine:
    name: Build and push - Fedora Golang diskimage    
    uses: ./.github/workflows/reusable-build-diskimage-machine.yml
    with:
      container_name: "base"
      base_from: "devfedora-cloud"
    secrets: inherit

  build-and-push-bootc:
    name: Build and push - Fedora Golang-bootc container
    uses: ./.github/workflows/reusable-build-and-push-bootable-container.yml
    with:
      container_name: "base"
    secrets: inherit

  build-diskimage-fedora-bootc:
    needs: 
      - build-and-push-bootc
    name: Build and push - Fedora Golang-bootc diskimage
    uses: ./.github/workflows/reusable-build-diskimage-bootc.yml
    with:
      container_name: "base"
    secrets: inherit
