name: build containers (bootc)
run-name: building containers (bootc)
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run podman build - base-bootc
        run: |
          podman build -t ghcr.io/gbraad-devenv/fedora-golang/base-bootc:41 \
            --build-arg=BASE_IMAGE="ghcr.io/gbraad-devenv/fedora/dotfiles-bootc" \
            --build-arg=BASE_VERSION=41 \
            -f containers/Containerfile-base .
      - name: Run podman build - dotfiles-bootc
        run: |
          podman build -t ghcr.io/gbraad-devenv/fedora-golang/dotfile-bootcs:41 \
            --build-arg=BASE_IMAGE="ghcr.io/gbraad-devenv/fedora-golang/base-bootc" \
            --build-arg=BASE_VERSION=41 \
            -f containers/Containerfile-dotfiles .
      - name: Run podman build - systemd-bootc
        run: |
          podman build -t ghcr.io/gbraad-devenv/fedora-golang/systemd-bootc:41 \
            --build-arg=BASE_IMAGE="ghcr.io/gbraad-devenv/fedora-golang/dotfiles-bootc" \
            --build-arg=BASE_VERSION=41 \
            -f containers/Containerfile-systemd .
      - name: Run podman build - code-cli-bootc
        run: |
          podman build -t ghcr.io/gbraad-devenv/fedora-golang/code-cli-bootc:41 \
            --build-arg=BASE_IMAGE="ghcr.io/gbraad-devenv/fedora-golang/systemd-bootc" \
            --build-arg=BASE_VERSION=41 \
            -f containers/Containerfile-code-cli .
      - name: Push image to ghcr.io - dotfiles-bootc
        run: |
          podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            ghcr.io/gbraad-devenv/fedora-golang/dotfiles-bootc:41
      - name: Push image to ghcr.io - systemd-bootc
        run: |
          podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            ghcr.io/gbraad-devenv/fedora-golang/systemd-bootc:41
      - name: Push image to ghcr.io - code-cli-bootc
        run: |
          podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            ghcr.io/gbraad-devenv/fedora-golang/code-cli-bootc:41